name: Run Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.MY_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.MY_AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: "us-east-1"
  # CONFIGURE YOUR TERRAFORM CLOUD TOKEN
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #- uses: hashicorp/setup-terraform@v2
      - name: Run Terraform Plan
        run: terraform plan
        working_directory: ./oct-31