name: Run Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: |
          echo my acces key id ${{ secrets.MY_AWS_ACCESS_KEY_ID }}
          echo my secret accces key ${{ secrets.MY_AWS_SECRET_ACCESS_KEY }}
